Add server_status metric
travelping/eradius pull request #208
Opened 2021-07-22 09:46 UTC by 0xAX

This PR contains following two changes:

The first commit improves fail-over mechansim.

When RADIUS client process is started it collects all secondary RADIUS servers from 
RADIUS server pools into ets table to use them for fail-over. The commit adds primary 
servers to this ets table. We need this to avoid following situation: A primary RADIUS 
server was used but eradius client failed to send requests there by some reasons. So 
such RADIUS server will be marked as inactive for a some configurable period of time 
and secondary RADIUS server will be used.

The issue is that eradius client could be used again with the primary server
while it is still in inactive state.
    
This commit adds all primary and secondary servers to an ets table that stores
currently active RADIUS servers. So if eradius client will be called with
currently inactive RADIUS server - it will not use it but try to search another
one which is active.

The second commit adds new `status_server` metric that represents an active or 
inactive state of a RADIUS server where eradius tries to send RADIUS requests. 

By default all possible endpoints are set to inactive. If eradius client sent a
request and received successfully response such primary/secondary
RADIUS server will be set to 'active' and that will be changed only
when next RADIUS request will be failed for this endpoint.
    
Backward compatibility is preserved and new functionality will be used only
in a case when fail-over is enabled.

2021-07-26 08:25 UTC, fholzhauser approved these changes

2021-07-26 11:57 UTC, vkatsuba requested changes
Detected error in `ergw_aaa:
```erlang
 =CRASH REPORT==== 26-Jul-2021::11:34:08.655365 ===
  crasher:
    initial call: eradius_counter:init/1
    pid: <0.6199.0>
    registered_name: []
    exception error: bad argument
      in function  ets:insert/2
         called as ets:insert(prometheus_registry_table,
                              {default,prometheus_boolean})
      in call from prometheus_registry:register_collector/2 (/__w/ergw_aaa/ergw_aaa/_build/default/lib/prometheus/src/prometheus_registry.erl, line 107)
      in call from prometheus_metric:insert_mf/3 (/__w/ergw_aaa/ergw_aaa/_build/default/lib/prometheus/src/prometheus_metric.erl, line 108)
      in call from eradius_counter:init/1 (/__w/ergw_aaa/ergw_aaa/_build/default/lib/eradius/src/eradius_counter.erl, line 146)
      in call from gen_server:init_it/2 (gen_server.erl, line 374)
      in call from gen_server:init_it/6 (gen_server.erl, line 342)
    ancestors: [eradius_sup,<0.6161.0>]
    ```

2021-07-26 12:55 UTC, 0xAX commented
The issue with tests in `ergw_aaa` is fixed.

2021-07-27 07:49 UTC, vkatsuba approved these changes

2021-07-27 07:51 UTC, merged