Bugfix/ipv6 handling
travelping/eradius pull request #216
Opened 2021-10-04 07:36 UTC by metelik

Changes:
- Fixing IPv6 parse function - IPv6 address is a tuple of 8 hextets (not 6)
- Adding AAAA class host-name resolution (:inet6)
- Adding switch between :inet and :inet6 address families for UDP client's socket opening based on the server's address

2021-10-04 07:38 UTC, vkatsuba reviewed
Hi. Thanks for your contribution! Please run GitHub Actions manually in your fork and provide here the link to success CI.
How to:

Open https://github.com/se-apc/eradius
Select tab Actions - https://github.com/se-apc/eradius/actions
Select tab CI
Find button Run workflow
Select in Run workflow branch master and click Run workflow

2021-10-04 07:45 UTC, vkatsuba reviewed
Please keep one code style - use 4 spaces instead of 2.

2021-10-04 07:45 UTC, vkatsuba reviewed
If you can, please provide test cases.

2021-10-04 08:09 UTC, RoadRunnr requested changes
You PR contains a merge commit. Please make sure that you only include you changes in the PR  and that the history is linear.

2021-10-04 08:09 UTC, RoadRunnr commented on src/eradius_client.erl
> +send_request({Host, Port, Secret}, Request, Options)
please, don't mix pure formatting and white space changes with functional changes.

If you think the whitespace problems need fixing, create a separate pull request for that.

2021-10-04 10:05 UTC, metelik commented
> 
> 
> If you can, please provide test cases.

Sure thing. I shall need to revisit some tests that have already been present due to the APIs changes. The functionality itself I had tested manually. I am not an Erlang major (not main main programming language)  so perhaps a joint effort in the expansion of the available test suite would be well appreciated.

2021-10-04 10:33 UTC, metelik commented
> 
> 
> You PR contains a merge commit. Please make sure that you only include your changes in the PR and that the history is linear.

QQ on this one. I shall have been probably merging the current master branch into our fork in any way so another merge commit shall appear. Would the commits' squashing into one do? I am asking because such a synchronisation with the upstream master can be advantageous on many levels. OOC what would be the reasons behind your disliking that?

2022-10-23 16:24 UTC, vkatsuba commented
Moved to https://github.com/travelping/eradius/pull/234

2022-10-23 16:24 UTC, closed without merging